services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "12345"
      DB_NAME: paw_follow
      DB_PORT: 3306
    depends_on:
      - db

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    depends_on:
      - backend

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=paw_follow
    ports:
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql